language: python
branches:
  only:
    - master
python:
  - "2.6"
  - "2.7"
  - "3.5"
install: "python setup.py install"
script: "python setup.py test -a tests.py"
notifications:
  email:
    on_success: change
    on_failure: change
